In [0]:
# Notebook para gerar os dados dos alunos de Caxias do Sul entre 2009 e 2018

In [0]:
!pip install patool # para descompactar arquivos .rar
!pip install fuzzywuzzy # para verficar a compatibilidade de palavras

     |████████████████████████████████| 81kB 2.6MB/s 


In [0]:
import pandas as pd
import numpy as np
pd.set_option('display.max_rows', 30000)

from zipfile import ZipFile # descompactar arquivos .zip
import os

import patoolib
from fuzzywuzzy import fuzz

/usr/local/lib/python3.6/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


In [0]:
# fazer a conexão com o google drive
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# pasta onde estão os dados
!ls '/content/drive/My Drive/inep'

microdados_censo_superior_2009.zip  microdados_censo_superior_2014.zip
microdados_censo_superior_2010.zip  microdados_censo_superior_2015.zip
microdados_censo_superior_2011.zip  microdados_censo_superior_2016.zip
microdados_censo_superior_2012.zip  microdados_educacao_superior_2017.zip
microdados_censo_superior_2013.zip  microdados_educacao_superior_2018.zip


In [0]:
anos = ['2009','2010','2011','2012','2013','2014','2015','2016','2017','2018']
directory = '/content/drive/My Drive/inep/'
zips = ['microdados_censo_superior_2009.zip',  
        'microdados_censo_superior_2010.zip',  
        'microdados_censo_superior_2011.zip',  
        'microdados_censo_superior_2012.zip',  
        'microdados_censo_superior_2013.zip',
        'microdados_censo_superior_2014.zip',
        'microdados_censo_superior_2015.zip',
        'microdados_censo_superior_2016.zip',
        'microdados_educacao_superior_2017.zip',
        'microdados_educacao_superior_2018.zip']

In [0]:
# criar as pastas para os dados de cada ano
for ano in anos:
  os.mkdir('/content/' + ano)

In [0]:
# descompactar os dados nas pastas criadas

for ano, cada in zip(anos, zips):
  caminho = directory + cada
  unzip = ZipFile(caminho)
  unzip.extractall(path = ano)

In [0]:
arquivos = ['/content/2009/2009/DADOS/DM_IES.rar',
             '/content/2010/DADOS/DM_IES.rar',
             '/content/2011/2011/DADOS/DM_IES.rar',
             '/content/2012/2012/DADOS/DM_IES.rar',
             '/content/2013/2013/DADOS/DM_IES.rar',
             '/content/2014/microdados_censo_superior_2014/2014/DADOS/DM_IES.CSV',
             '/content/2015/microdados_censo_superior_2015/DADOS/DM_IES.rar',
             '/content/2016/DADOS/DM_IES.rar',
             '/content/2017/Microdados_Educacao_Superior_2017/DADOS/DM_IES.zip',
             '/content/2018/microdados_ed_superior_2018/dados/DM_IES.CSV',
              '/content/2009/2009/DADOS/DM_ALUNO.rar',
              '/content/2010/DADOS/DM_ALUNO.rar',
              '/content/2011/2011/DADOS/DM_ALUNO.rar',
              '/content/2012/2012/DADOS/DM_ALUNO.rar',
              '/content/2013/2013/DADOS/DM_ALUNO.rar',
              '/content/2014/microdados_censo_superior_2014/2014/DADOS/DM_ALUNO.CSV',
              '/content/2015/microdados_censo_superior_2015/DADOS/DM_ALUNO.rar',
              '/content/2016/DADOS/DM_ALUNO.rar',
              '/content/2017/Microdados_Educacao_Superior_2017/DADOS/DM_ALUNO.zip',
              '/content/2018/microdados_ed_superior_2018/dados/DM_ALUNO.CSV']

In [0]:
# em alguns anos os dados estão compactados em arquivo .rar e em outros .zip
for arquivo in arquivos:
  caminho_saida = arquivo[:arquivo.index('/DM')]
  
  if arquivo.endswith('.rar') == True:
    patoolib.extract_archive(arquivo, outdir = caminho_saida)
    
  elif arquivo.endswith('.zip') == True:
    unzip = ZipFile(arquivo)
    unzip.extractall(path = caminho_saida)

patool: Extracting /content/2009/2009/DADOS/DM_IES.rar ...
patool: running /usr/bin/unrar x -- /content/2009/2009/DADOS/DM_IES.rar
patool:     with cwd='/content/2009/2009/DADOS'
patool: ... /content/2009/2009/DADOS/DM_IES.rar extracted to `/content/2009/2009/DADOS'.
patool: Extracting /content/2010/DADOS/DM_IES.rar ...
patool: running /usr/bin/unrar x -- /content/2010/DADOS/DM_IES.rar
patool:     with cwd='/content/2010/DADOS'
patool: ... /content/2010/DADOS/DM_IES.rar extracted to `/content/2010/DADOS'.
patool: Extracting /content/2011/2011/DADOS/DM_IES.rar ...
patool: running /usr/bin/unrar x -- /content/2011/2011/DADOS/DM_IES.rar
patool:     with cwd='/content/2011/2011/DADOS'
patool: ... /content/2011/2011/DADOS/DM_IES.rar extracted to `/content/2011/2011/DADOS'.
patool: Extracting /content/2012/2012/DADOS/DM_IES.rar ...
patool: running /usr/bin/unrar x -- /content/2012/2012/DADOS/DM_IES.rar
patool:     with cwd='/content/2012/2012/DADOS'
patool: ... /content/2012/2012/DADOS/DM_IE

In [0]:
# caminhos dos dados

path_ies = ['/content/2009/2009/DADOS/DM_IES.CSV',
           '/content/2010/DADOS/DM_IES.CSV',
           '/content/2011/2011/DADOS/DM_IES.CSV',
           '/content/2012/2012/DADOS/DM_IES.CSV',
           '/content/2013/2013/DADOS/DM_IES.CSV',
           '/content/2014/microdados_censo_superior_2014/2014/DADOS/DM_IES.CSV',
           '/content/2015/microdados_censo_superior_2015/DADOS/DM_IES.CSV',
           '/content/2016/DADOS/DM_IES.CSV',
           '/content/2017/Microdados_Educacao_Superior_2017/DADOS/DM_IES.CSV',
           '/content/2018/microdados_ed_superior_2018/dados/DM_IES.CSV']

path_alunos = ['/content/2009/2009/DADOS/DM_ALUNO.CSV',
              '/content/2010/DADOS/DM_ALUNO.CSV',
              '/content/2011/2011/DADOS/DM_ALUNO.CSV',
              '/content/2012/2012/DADOS/DM_ALUNO.CSV',
              '/content/2013/2013/DADOS/DM_ALUNO.CSV',
              '/content/2014/microdados_censo_superior_2014/2014/DADOS/DM_ALUNO.CSV',
              '/content/2015/microdados_censo_superior_2015/DADOS/DM_ALUNO.CSV',
              '/content/2016/DADOS/DM_ALUNO.CSV',
              '/content/2017/Microdados_Educacao_Superior_2017/DADOS/DM_ALUNO.CSV',
              '/content/2018/microdados_ed_superior_2018/dados/DM_ALUNO.CSV']

In [0]:
# Essa parte é para pegar os códigos das IES de Caxias e
# associar esses códigos aos nomes das IES.
# A UCS tem o código 13 por exemplo

codigo_ibge_caxias = 4305108 # código do IBGE de Caxias
codigos_ies_caxias = []
nomes_ies_caxias = []

for each in path_ies:
  dummy = pd.read_csv(each, delimiter = '|', encoding = 'latin1')
  for coluna in dummy.columns:
    comparacao = 'CO_MUNICIPIO'
    if fuzz.partial_ratio(comparacao, coluna) >= 95:
      dummy.rename({coluna: comparacao}, axis = 1, inplace = True)
  caxias = (dummy[comparacao] == codigo_ibge_caxias)
  ies_caxias = dummy.loc[caxias,:].copy()
  
  codigos = ies_caxias.CO_IES
  nomes = ies_caxias.NO_IES
  
  nomes_ies_caxias.append(dict(zip(codigos, nomes))) # gerando uma lista de dicionários com os códigos e nomes das IES 
  
  codigos_ies_caxias.append(codigos.unique())

In [0]:
# cógigos das ies de caxias em cada ano

codigos_ies_caxias

[array([  13, 2826, 3333, 4616, 1969, 3596, 1427, 4632]),
 array([   13,  1427,  1969,  2826,  3333,  3596,  4616,  4632, 11563]),
 array([ 1427,  1969,    13,  2826, 11563,  3596,  3333,  4632,  4616]),
 array([ 2826,  3596,    13, 11563,  4616, 13883,  3333,  4632,  1427,
         1969]),
 array([ 1969, 13818, 13883,  3596,  2826, 11563,  4632,    13,  1427,
         3333,  4616]),
 array([   13, 13818,  4632,  1427,  3596,  2826,  3333,  4616, 11563,
        13883]),
 array([   13,  1427,  3333,  3596,  2826, 11563,  4616,  4632, 13818,
        13883]),
 array([   13, 13818,  1427,  3596,  2826,  3333,  4616, 11563, 13883,
         4632]),
 array([   13, 11563,  1427,  2826,  3333, 13883,  4632,  4616]),
 array([   13, 11563,  1427,  2826,  3333, 13883,  4632,  4616])]

In [0]:
nomes_ies_caxias

[{13: 'UNIVERSIDADE DE CAXIAS DO SUL',
  1427: 'FACULDADE DA SERRA GAUCHA',
  1969: 'FACULDADE DOS IMIGRANTES  FAI',
  2826: 'FACULDADE NOSSA SENHORA DE FATIMA',
  3333: 'FACULDADE DE TECNOLOGIA TECBRASIL',
  3596: 'FACULDADE MONTSERRAT',
  4616: 'FACULDADE ANHANGUERA DE CAXIAS DO SUL',
  4632: 'FACULDADE ANGLOAMERICANO DE CAXIAS DO SUL'},
 {13: 'UNIVERSIDADE DE CAXIAS DO SUL',
  1427: 'FACULDADE DA SERRA GAÚCHA',
  1969: 'FACULDADE DOS IMIGRANTES - FAI',
  2826: 'FACULDADE NOSSA SENHORA DE FÁTIMA',
  3333: 'FACULDADE DE TECNOLOGIA TECBRASIL',
  3596: 'FACULDADE AMÉRICA LATINA',
  4616: 'FACULDADE ANHANGUERA DE CAXIAS DO SUL',
  4632: 'FACULDADE ANGLO-AMERICANO DE CAXIAS DO SUL',
  11563: 'FACULDADE DE TECNOLOGIA DA SERRA GAÚCHA - CAXIAS DO SUL'},
 {13: 'UNIVERSIDADE DE CAXIAS DO SUL',
  1427: 'FACULDADE DA SERRA GAÚCHA',
  1969: 'FACULDADE DOS IMIGRANTES - FAI',
  2826: 'FACULDADE NOSSA SENHORA DE FÁTIMA',
  3333: 'FACULDADE DE TECNOLOGIA TECBRASIL',
  3596: 'FACULDADE AMÉRICA LATINA'

In [0]:
# As colunas em cada ano possuem pequenas mudanças nos nomes o que dificulta a automação dos procedimentos.
# Existe um arquivo excel (Dicionário de Variáveis) em cada ano que mostra a explicação do que significa cada coluna.

lista_colunas = [['CO_IES', # 2009
           'CO_GRAU_ACADEMICO',
           'CO_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'CO_ALUNO_SITUACAO',
           'CO_ALUNO',
           'CO_NIVEL_ACADEMICO',
           'IN_SEXO_ALUNO'],
                 
                ['CO_IES', #2010
           'CO_GRAU_ACADEMICO',
           'CO_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'CO_ALUNO_SITUACAO',
           'CO_ALUNO',
           'CO_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', #2011
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'CO_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', #2012
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'DS_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', # 2013
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'DS_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', # 2014
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'DS_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', # 2015
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'DS_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_IES', # 2016
           'DS_GRAU_ACADEMICO',
           'DS_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NO_CURSO',
           'NU_IDADE_ALUNO',
           'ANO_INGRESSO',
           'DS_ALUNO_SITUACAO',
           'CO_ALUNO',
           'DS_NIVEL_ACADEMICO',
           'DS_SEXO_ALUNO'],
                 
                ['CO_ALUNO', #2017 
           'NU_ANO_CENSO',
           'CO_IES',
           'TP_GRAU_ACADEMICO', 
           'TP_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NU_IDADE', 
           'NU_ANO_INGRESSO', 
           'TP_SITUACAO', 
           'TP_NIVEL_ACADEMICO',
           'TP_SEXO'],
                 
                ['ID_ALUNO', # 2018
           'NU_ANO_CENSO',
           'CO_IES',
           'TP_GRAU_ACADEMICO',
           'TP_MODALIDADE_ENSINO',
           'CO_CURSO',
           'NU_IDADE', 
           'NU_ANO_INGRESSO', 
           'TP_SITUACAO', 
           'TP_NIVEL_ACADEMICO',
           'TP_SEXO']]

In [0]:
nomes_arquivos = ['alunos_caxias_{}'.format(x) for x in range(2009,2019)]
nomes_arquivos

['alunos_caxias_2009',
 'alunos_caxias_2010',
 'alunos_caxias_2011',
 'alunos_caxias_2012',
 'alunos_caxias_2013',
 'alunos_caxias_2014',
 'alunos_caxias_2015',
 'alunos_caxias_2016',
 'alunos_caxias_2017',
 'alunos_caxias_2018']

In [0]:
# Aqui é feita a importação dos dados dos alunos.
# Como são arquivos csv muito grandes, entre 3 e 5 GB,
# é preciso abrir os arquivos em pedaços para não usar toda a memória.
# Para fazer isso, o parametro chunksize é usado em pd.read_csv.
# DEMORA CERCA DE 15 MINUTOS PARA RODAR

for linhas, colunas, alunos, nome in zip(codigos_ies_caxias, lista_colunas, path_alunos, nomes_arquivos):
  chunks = pd.read_csv(alunos, 
                     delimiter = '|', encoding = 'latin1', chunksize = 500_000)
  
  dataframes = []

  for chunk in chunks:
    filtro = chunk.loc[chunk.CO_IES.isin(linhas), colunas].copy()
    dataframes.append(filtro)

  vars()[nome] = pd.concat(dataframes)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
dataframes = [alunos_caxias_2009,
             alunos_caxias_2010,
             alunos_caxias_2011,
             alunos_caxias_2012,
             alunos_caxias_2013,
             alunos_caxias_2014,
             alunos_caxias_2015,
             alunos_caxias_2016,
             alunos_caxias_2017,
             alunos_caxias_2018]

In [0]:
alunos_caxias_2009.head()

CO_IES  CO_GRAU_ACADEMICO  ...  CO_NIVEL_ACADEMICO  IN_SEXO_ALUNO
103      13                1.0  ...                   1              1
355      13                3.0  ...                   1              0
637      13                1.0  ...                   1              1
699      13                1.0  ...                   1              1
700    1427                1.0  ...                   1              1

[5 rows x 11 columns]

In [0]:
alunos_caxias_2010.head()

CO_IES  CO_GRAU_ACADEMICO  ...  CO_NIVEL_ACADEMICO  DS_SEXO_ALUNO
20087      13                2.0  ...                   1      Masculino
20088      13                2.0  ...                   1       Feminino
20089      13                2.0  ...                   1      Masculino
20090      13                2.0  ...                   1      Masculino
20091      13                2.0  ...                   1       Feminino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2011.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
12     3596       Bacharelado  ...          Graduação       Feminino
214      13       Bacharelado  ...          Graduação       Feminino
675    1969       Bacharelado  ...          Graduação      Masculino
757    1969       Bacharelado  ...          Graduação      Masculino
836    1969       Bacharelado  ...          Graduação      Masculino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2012.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
35     1969       Bacharelado  ...          Graduação       Feminino
357    1427       Bacharelado  ...          Graduação      Masculino
467      13       Bacharelado  ...          Graduação      Masculino
875    4632       Bacharelado  ...          Graduação      Masculino
934    4632       Bacharelado  ...          Graduação       Feminino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2013.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
303193      13      Licenciatura  ...          Graduação       Feminino
303194      13      Licenciatura  ...          Graduação      Masculino
303195      13      Licenciatura  ...          Graduação      Masculino
303196      13      Licenciatura  ...          Graduação       Feminino
303197      13      Licenciatura  ...          Graduação      Masculino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2014.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
116669      13      Licenciatura  ...          Graduação      Masculino
116670      13      Licenciatura  ...          Graduação       Feminino
116671      13      Licenciatura  ...          Graduação       Feminino
116672      13      Licenciatura  ...          Graduação       Feminino
116673      13      Licenciatura  ...          Graduação      Masculino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2015.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
307108      13       Bacharelado  ...          Graduação       Feminino
307109      13       Tecnológico  ...          Graduação      Masculino
307110      13       Bacharelado  ...          Graduação       Feminino
307111      13       Bacharelado  ...          Graduação       Feminino
307112      13       Bacharelado  ...          Graduação       Feminino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2016.head()

CO_IES DS_GRAU_ACADEMICO  ... DS_NIVEL_ACADEMICO  DS_SEXO_ALUNO
309057      13      Licenciatura  ...          Graduação       Feminino
309058      13      Licenciatura  ...          Graduação      Masculino
309059      13      Licenciatura  ...          Graduação      Masculino
309060      13      Licenciatura  ...          Graduação       Feminino
309061      13      Licenciatura  ...          Graduação       Feminino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2017.head()

CO_ALUNO  NU_ANO_CENSO  ...  TP_NIVEL_ACADEMICO  TP_SEXO
305644  400001555899          2017  ...                   1        2
305645  400001660567          2017  ...                   1        2
305646  400001911533          2017  ...                   1        1
305647  400003107087          2017  ...                   1        2
305648  400003177276          2017  ...                   1        1

[5 rows x 11 columns]

In [0]:
alunos_caxias_2018.head()

ID_ALUNO  ...  TP_SEXO
296263  71CCAB7D5BAE6603B3995CA2EB8F9534  ...        2
296264  FBC7BF40B3F9AC1C46F78CFF70AC141B  ...        2
296265  43ABA22A4C7DC2F6E69C71CE90D339A0  ...        2
296266  10707CB293B32AD1BC23EB641765BCE7  ...        1
296267  7C95F1E0E536524DC3281C4452030F72  ...        1

[5 rows x 11 columns]

In [0]:
renomear_colunas = {'CO_NIVEL_ACADEMICO': 'TP_NIVEL_ACADEMICO',
                    'CO_ALUNO_SITUACAO':'TP_SITUACAO',
                    'DS_NIVEL_ACADEMICO': 'TP_NIVEL_ACADEMICO',
                    'DS_ALUNO_SITUACAO': 'TP_SITUACAO',
                    'NU_ANO_INGRESSO': 'ANO_INGRESSO',
                    'DS_GRAU_ACADEMICO': 'TP_GRAU_ACADEMICO',
                    'CO_GRAU_ACADEMICO': 'TP_GRAU_ACADEMICO',
                     'DS_SEXO_ALUNO': 'TP_SEXO',
                     'IN_SEXO_ALUNO': 'TP_SEXO',
                     'DS_MODALIDADE_ENSINO': 'TP_MODALIDADE_ENSINO',
                     'CO_MODALIDADE_ENSINO': 'TP_MODALIDADE_ENSINO'}

for df in dataframes:
  df.rename(renomear_colunas, axis = 1, inplace=True)

In [0]:
# dicionários para fazer as mudanças dos códigos para o que eles significam nos dados de 2009, 2010, 2011, 2017 e 2018 

genero_2009 = {0: 'Masculino',
              1: 'Feminino'}

genero_2017_2018 = {2: 'Masculino',
                    1: 'Feminino'}

situacao = {1: 'Provável Formando', # essa descrição só está nos dados de 2009
            2: 'Cursando',
            3: 'Matrícula trancada',
            4: 'Desvinculado do curso',
            5: 'Transferido para outro curso da mesma IES',
            6: 'Formado',
            7: 'Falecido'}

grau = {1: 'Bacharelado',
        2: 'Licenciatura',
        3: 'Tecnólogo',
        4: 'Bacharelado e Licenciatura'} # só no dados de 2009

modalidade = {1: 'Presencial',
              2: 'a distância'}

nivel = {1: 'Graduação',
         2: 'Sequencial de Formação'}

In [0]:
# formatações 2009, 2010 e 2011

dados = [alunos_caxias_2009, alunos_caxias_2010, alunos_caxias_2011]

cols = ['TP_SEXO','TP_SITUACAO','TP_GRAU_ACADEMICO', 'TP_MODALIDADE_ENSINO', 'TP_NIVEL_ACADEMICO']
dicis = [genero_2009, situacao, grau, modalidade, nivel]


for data in dados:  
  for col, dic in zip(cols, dicis):
    data[col].replace(dic, inplace = True)

In [0]:
# formatações 2017 e 2018

dados = [alunos_caxias_2017, alunos_caxias_2018]

cols = ['TP_SEXO','TP_SITUACAO','TP_GRAU_ACADEMICO', 'TP_MODALIDADE_ENSINO', 'TP_NIVEL_ACADEMICO']
dicis = [genero_2017_2018, situacao, grau, modalidade, nivel]


for data in dados:  
  for col, dic in zip(cols, dicis):
    data[col].replace(dic, inplace = True)
    
# os outros anos já estão no formato desejado

In [0]:
alunos_caxias_2009.head(2)

CO_IES TP_GRAU_ACADEMICO  ... TP_NIVEL_ACADEMICO    TP_SEXO
103      13       Bacharelado  ...          Graduação   Feminino
355      13         Tecnólogo  ...          Graduação  Masculino

[2 rows x 11 columns]

In [0]:
alunos_caxias_2010.head(2)

CO_IES TP_GRAU_ACADEMICO  ... TP_NIVEL_ACADEMICO    TP_SEXO
20087      13      Licenciatura  ...          Graduação  Masculino
20088      13      Licenciatura  ...          Graduação   Feminino

[2 rows x 11 columns]

In [0]:
alunos_caxias_2011.head(2)

CO_IES TP_GRAU_ACADEMICO  ... TP_NIVEL_ACADEMICO   TP_SEXO
12     3596       Bacharelado  ...          Graduação  Feminino
214      13       Bacharelado  ...          Graduação  Feminino

[2 rows x 11 columns]

In [0]:
alunos_caxias_2017.head(2)

CO_ALUNO  NU_ANO_CENSO  ...  TP_NIVEL_ACADEMICO    TP_SEXO
305644  400001555899          2017  ...           Graduação  Masculino
305645  400001660567          2017  ...           Graduação  Masculino

[2 rows x 11 columns]

In [0]:
alunos_caxias_2018.head(2)

ID_ALUNO  ...    TP_SEXO
296263  71CCAB7D5BAE6603B3995CA2EB8F9534  ...  Masculino
296264  FBC7BF40B3F9AC1C46F78CFF70AC141B  ...  Masculino

[2 rows x 11 columns]

In [0]:
# Ainda é preciso colcar os nomes das IES para todos os anos
# e colocar os nomes dos cursos.
# Esses dicionarios foram criados usando os dados dos cursos e também com o site do e-MEC para 
# pegar os nomes dos cursos em que só tinham os códigos.

dicionario_cursos = np.load('dicionario_cursos.npy', allow_pickle = True).item()
dicionario_cursos_faltantes = np.load('dicionario_cursos_faltantes.npy', allow_pickle = True).item()

In [0]:
# colocar os nomes das IES em todos os dados
for nomes, df in zip(nomes_ies_caxias, dataframes):
  df['CO_IES'].replace(nomes, inplace = True)

In [0]:
# colocar os nomes dos cursos para os anos de 2017 e 2018

for df in [alunos_caxias_2017, alunos_caxias_2018]:
  for dici in [dicionario_cursos, dicionario_cursos_faltantes]:
    df['CO_CURSO'].replace(dici, inplace = True)  

In [0]:
alunos_caxias_2017.head()

CO_ALUNO  NU_ANO_CENSO  ... TP_NIVEL_ACADEMICO    TP_SEXO
305644  400001555899          2017  ...          Graduação  Masculino
305645  400001660567          2017  ...          Graduação  Masculino
305646  400001911533          2017  ...          Graduação   Feminino
305647  400003107087          2017  ...          Graduação  Masculino
305648  400003177276          2017  ...          Graduação   Feminino

[5 rows x 11 columns]

In [0]:
alunos_caxias_2018.head()

ID_ALUNO  ...    TP_SEXO
296263  71CCAB7D5BAE6603B3995CA2EB8F9534  ...  Masculino
296264  FBC7BF40B3F9AC1C46F78CFF70AC141B  ...  Masculino
296265  43ABA22A4C7DC2F6E69C71CE90D339A0  ...  Masculino
296266  10707CB293B32AD1BC23EB641765BCE7  ...   Feminino
296267  7C95F1E0E536524DC3281C4452030F72  ...   Feminino

[5 rows x 11 columns]

In [0]:
# Trocar o nome da coluna dos cursos para os dados de 2017 e 2018.
# Deixar padronizado com os outros anos.
for data in [alunos_caxias_2017, alunos_caxias_2018]:
  data.rename({'CO_CURSO': 'NO_CURSO'}, axis = 1, inplace = True)

In [0]:
# tirar a caixa alta dos nomes das IES e cursos
for df in dataframes: 
  for coluna in ['CO_IES', 'NO_CURSO']:
    df[coluna] = df[coluna].map(lambda x: str(x).title())
  

In [0]:
# salvar os arquivos em csv

for df, nome_arquivo in zip(dataframes, nomes_arquivos):
  df.to_csv(nome_arquivo + '.csv', index = False)